@TerralertAPI_HostAddress = http://localhost:5210

GET {{TerralertAPI_HostAddress}}/api/storms/current/
Accept: application/json

###

GET {{TerralertAPI_HostAddress}}/api/earthquakes/current/
Accept: application/json

###

GET {{TerralertAPI_HostAddress}}/api/wildfires/current/
Accept: application/json

###

GET {{TerralertAPI_HostAddress}}/api/volcanoes/current/
Accept: application/json

###